### ISSUE TITLE
Screenshot in readme

### ISSUE THREAD

**Issue by sarfraznawaz2005** [mobiosolutions/ms-bootstrap-admin#1]
This is not an issue but it would be good to have screenshot in readme so we can see how it looks before cloning it. Thanks

**Comment by mobiosolutions** [comment]
Hi @sarfraznawaz2005 , we are working on it and will update it soon.

**Comment by mobiosolutions** [comment]
> Hi @sarfraznawaz2005 , we are working on it and will update it soon.

Screenshot has been update. Thanks for feedback.
